### ISSUE TITLE
Order of numbered tables

### ISSUE THREAD

**Issue by florisvdh** [inbo/INBOmd#28]
In the report example of [INBOmd_examples](https://github.com/inbo/inbomd_examples) several (nice!) tables are generated. They get a table number. LaTeX places them in a different order, e.g. 12.3 -> 12.1 -> 12.2. This should be avoided in my opinion; I guess this will not conform to INBO standards. In other words, tables may float but they should not 'jump' one over another.

Maybe the same problem can occur with figures.

**Comment by ThierryO** [comment]
This is something you can't force in the style. The user has to be vigilant about this. However, in practice users will be unlikely to mixed different styles of tables in the same section. Hence the problem is less likely to occur.

In case it does occur, the user can fix it by placing a \FloatBarrier at the proper place (in this case before placing table 12.3). This is described in §7.3.
