### ISSUE TITLE
prevent subsection title + lone sentence at end of page (pdf output inbo_rapport)

### ISSUE THREAD

**Issue by hansvancalster** [inbo/INBOmd#44]
````
---
title: "Titel van het rapport"
site: bookdown::bookdown_site
output:
  bookdown::pdf_book:
    base_format: INBOmd::inbo_rapport
---


# Section

```{r results="asis", echo=FALSE}
cat(rep("a sentence", 27), sep = "\n", fill = 10)
```


## Subsection

Here are some points to consider:

- point 1
- point 2
- point 3

````

**Comment by ThierryO** [comment]
This is hard to solve because you want to keep three items together. In your first example you want the section and the list to keep together. In the second example the section and the last paragraph should be together.

A workaround is to add a `\needspace{measurement}`, e.g. `\needspace{30mm}`. This will calculate the remaning space on the page. If there is not enough vertical space, it will insert a pagebreak.

**Comment by hansvancalster** [comment]
That's a nice solution. @florisvdh pinging to you to make sure you read this. Closing the issue.
