### ISSUE TITLE
inbo_rapport: line spacing & underline in title / subtitle

### ISSUE THREAD

**Issue by florisvdh** [inbo/INBOmd#73]
After compiling bookdown project https://github.com/inbo/osd/tree/624f2fe/src using INBOmd at 595845a (currently on branch `0.4.10`), on the title page we get much line space:

![afbeelding](https://user-images.githubusercontent.com/19164640/114420740-dda61600-9bb4-11eb-8ae9-78e582c9f1e6.png)

This PDF was afterwards edited by our layouter to the below result. I guess that both linespacing (title+subtitle) and underlining (for the title) need to be changed in INBOmd.

![afbeelding](https://user-images.githubusercontent.com/19164640/114421076-37a6db80-9bb5-11eb-8591-b19172072c01.png)

**Comment by ThierryO** [comment]
We tried to underline in the [past](https://github.com/inbo/INBOmd/blob/2550a5e9292fee059aa8a77359650a83ffbf117c/inst/local_tex/tex/latex/inborapport_2015/flanders_report_generic.sty#L397). We had to undo that because it breaks proper line breaking. It works only for short title.

And IMHO, underlining is old fashioned. This stems from the age of typewriters when you couldn't change the font.

**Comment by florisvdh** [comment]
> it breaks proper line breaking

> underlining is old fashioned

I believe these are valuable arguments. So I think there's a need to have broader discussion (maybe INBO level) about the report style itself.
